// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calc_prox
DataFrame calc_prox(NumericMatrix map, double cell_size, double alpha);
RcppExport SEXP _proximity2_calc_prox(SEXP mapSEXP, SEXP cell_sizeSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type map(mapSEXP);
    Rcpp::traits::input_parameter< double >::type cell_size(cell_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_prox(map, cell_size, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_proximity2_calc_prox", (DL_FUNC) &_proximity2_calc_prox, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_proximity2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
