# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_prox <- function(map, cell_size, alpha) {
    .Call('_proximity2_calc_prox', PACKAGE = 'proximity2', map, cell_size, alpha)
}

